// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProsumerInfo.Models;

namespace ProsumerInfo.Migrations
{
    [DbContext(typeof(ProsumerInfoContext))]
    [Migration("20181214142533_2ndTry")]
    partial class _2ndTry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProsumerInfo.Models.Consumption", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Consumption_time");

                    b.Property<string>("KWH");

                    b.HasKey("id");

                    b.ToTable("Consumption");
                });

            modelBuilder.Entity("ProsumerInfo.Models.Production", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KWH");

                    b.Property<string>("ProductionTime");

                    b.HasKey("id");

                    b.ToTable("Production");
                });

            modelBuilder.Entity("ProsumerInfo.Models.Prosumer", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProsumerType");

                    b.Property<string>("X10_ID");

                    b.HasKey("id");

                    b.ToTable("Prosumer");
                });

            modelBuilder.Entity("ProsumerInfo.Models.ProsumerConsumption", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PC_Timestamp");

                    b.Property<string>("ProsumerBalance");

                    b.HasKey("id");

                    b.ToTable("ProsumerConsumption");
                });
#pragma warning restore 612, 618
        }
    }
}
